download_dir = "./output"
post_count = 32
base_url = "https://e621.net"
output_format = "$artist/$rating/$tags[2] - $id - $date $time - $score.$ext"

[display]
width = 480

[http]
max_connections = 100
