[package]
name = "e62rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
e6cfg = { version = "0.1.0", path = "../e6cfg" }
e6core = { version = "0.1.0", path = "../e6core" }
e6ui = { version = "0.1.0", path = "../e6ui" }
env_logger = "0.11.8"
log = "0.4.28"
tokio = { version = "1.47.1", features = ["full"] }
