[package]
name = "e6cfg"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.42"
config = "0.15.16"
log = "0.4.28"
serde = { version = "1.0.226", features = ["derive"] }
toml = "0.9.7"
